import {STORAGE_KEY,LocalRepository,freshState,applyCommand,activeRound,strokeSummary,poolFor,normalizeIndex,levelName,wildcardOptions} from './model.js';
const $=id=>document.getElementById(id);
let repo,state,blocked=false,storageFault=false,rolling=false,index=0,timer=null,saveQueue=Promise.resolve();
const initialText=(node,value)=>{node.textContent=value;};
const announce=text=>initialText($('announcer'),text);
function notice(text){$('notice').textContent=text;$('notice').hidden=!text;}
try{repo=new LocalRepository(localStorage);state=repo.load()??freshState();}catch(error){state=freshState();blocked=true;notice('Saved data could not be opened. Export a backup before troubleshooting. Existing data has not been replaced.');}
const inProgress=()=>state.draft&&state.draft.stage!=='complete';
const activePlayer=()=>state.players.find(p=>p.id===state.activePlayerId);
const hole=()=>activeRound(state).holes.find(h=>h.id===state.activeHoleId);
// Web Locks serializes writes from tabs of this origin; revisions reject stale
// changes. This is local concurrency protection, not multi-device synchronization.
function commit(type,payload={}){
 saveQueue=saveQueue.catch(()=>{}).then(async()=>{
  if(blocked)throw new Error('Saved data needs attention. Export a backup and reload.');
  const write=()=>{const next=applyCommand(state,type,payload);repo.save(next,state.revision);state=next;storageFault=false;return next;};
  try {const next=navigator.locks?await navigator.locks.request('disc-roller-write',write):write();$('saveStatus').textContent='Saved on this device · '+new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});return next;}
  catch(error){storageFault=true;stopTimer();notice(error.message.includes('another tab')?error.message:'Could not save this change. Your previous saved data is intact. Export a backup, free storage if needed, then reload.');$('saveStatus').textContent='Change not saved';throw error;}
 });return saveQueue;
}
function stopTimer(){clearInterval(timer);timer=null;rolling=false;}
function drawReel(){if(!inProgress()||state.draft.wildcard)return;const pool=poolFor(state.draft.stage,state.preferences.experience);index=normalizeIndex(index,pool.length);$('reelText').textContent=pool[index]==='WILDCARD'?'WILD CARD':pool[index];}
function startTimer(){stopTimer();rolling=true;drawReel();timer=setInterval(()=>{const pool=poolFor(state.draft.stage,state.preferences.experience);index=(index+1)%pool.length;drawReel();},60);}
function renderMachine(){
 const d=state.draft;const current=activePlayer();const round=activeRound(state);const busy=!!inProgress();
 $('turnLabel').textContent=current?current.name.toUpperCase()+', YOU’RE UP':'READY, PLAYER ONE?';$('roundLabel').textContent='ROUND '+(state.rounds.indexOf(round)+1);
 $('currentPlayerLabel').textContent=current?.name??'Free play';
 $('activeHole').replaceChildren(...round.holes.map(h=>{const o=document.createElement('option');o.value=h.id;o.textContent='Hole '+h.number;return o;}));$('activeHole').value=state.activeHoleId;$('activeHole').disabled=busy||blocked;
 $('idleDisplay').hidden=!!d;$('reelDisplay').hidden=!busy||!!d?.wildcard;$('wildDisplay').hidden=!d?.wildcard;$('completeDisplay').hidden=d?.stage!=='complete';
 for(const stage of ['disc','stability','shot']){$('result-'+stage).textContent=d?.[stage]??'—';$('slot-'+stage).classList.toggle('active',d?.stage===stage);$('slot-'+stage).classList.toggle('locked',!!d?.[stage]);}
 $('difficulty').value=state.preferences.experience;$('difficultyName').textContent=levelName(state.preferences.experience);$('difficulty').disabled=blocked;
 if(busy&&!d.wildcard){$('reelStage').textContent=({disc:'01 / DISC TYPE',stability:'02 / STABILITY',shot:'03 / SHOT TYPE'})[d.stage];drawReel();}
 if(d?.wildcard){$('wildTitle').textContent=({disc:'Pick your disc.',stability:'Pick stability.',shot:'Pick your shot.'})[d.stage];$('wildOptions').replaceChildren(...wildcardOptions(d.stage).map(value=>{const button=document.createElement('button');button.type='button';button.textContent=value;button.addEventListener('click',()=>choose(value));return button;}));}
 if(d?.stage==='complete')$('completePlayer').textContent=(current?.name??'Free play')+' · Hole '+hole().number;
 $('mainAction').hidden=!!d?.wildcard;$('mainAction').disabled=blocked;$('mainAction').classList.toggle('is-rolling',busy&&rolling);$('actionLabel').textContent=!d?'START ROLLING':d.stage==='complete'?'ROLL AGAIN':rolling?'STOP THE REEL':'RESUME REEL';$('actionIcon').textContent=rolling?'■':'↗';
 $('controlHint').textContent=d?.wildcard?'Wild cards can choose beyond your difficulty level.':d?.stage==='complete'?'Enter your strokes below, or pick the next player.':busy&&!rolling?'Your challenge is saved. Resume when you’re ready.':'Tap to play · Space or Enter on the focused button';
 $('newNightButton').disabled=busy||blocked;
}
function renderPlayers(){
 const round=activeRound(state);const players=state.players.filter(p=>round.playerIds.includes(p.id));$('playerCount').textContent=String(players.length).padStart(2,'0');$('emptyPlayers').hidden=players.length>0;
 $('playerList').replaceChildren(...players.map((p,i)=>{const button=document.createElement('button');button.className='player-row'+(p.id===state.activePlayerId?' selected':'');button.type='button';button.setAttribute('aria-pressed',String(p.id===state.activePlayerId));button.disabled=!!inProgress()||blocked;const avatar=document.createElement('span');avatar.className='avatar';avatar.textContent=String(i+1).padStart(2,'0');avatar.setAttribute('aria-hidden','true');const info=document.createElement('span');info.className='player-info';const name=document.createElement('span');name.className='player-name';name.textContent=p.name;const meta=document.createElement('span');meta.className='player-meta';const summary=strokeSummary(round,p.id);meta.textContent=summary.played?`${summary.total} strokes · ${summary.played}/${summary.holes} holes`:'Ready for the first throw';info.append(name,meta);button.append(avatar,info);if(p.id===state.activePlayerId){const turn=document.createElement('span');turn.className='player-turn';turn.textContent='UP NEXT';button.append(turn);}button.addEventListener('click',async()=>{try{await commit('player.select',{playerId:p.id});render();}catch{}});return button;}));
 $('playerName').disabled=!!inProgress()||blocked;$('playerForm').querySelector('button').disabled=!!inProgress()||blocked;
}
function renderScores(){
 const round=activeRound(state);$('scoreDescription').textContent=`${round.holes.length} holes · Total strokes · Lower is better`;$('scoreEmpty').hidden=round.playerIds.length>0;$('scoreTableWrap').hidden=!round.playerIds.length;
 const table=$('scoreTable');table.replaceChildren();const caption=document.createElement('caption');caption.className='sr-only';caption.textContent='Stroke scores for round '+(state.rounds.indexOf(round)+1)+'. Blank means unplayed. Totals may be partial.';table.append(caption);
 const head=document.createElement('thead');const hr=document.createElement('tr');for(const label of ['PLAYER',...round.holes.map(h=>'H'+h.number),'TOTAL']){const th=document.createElement('th');th.scope='col';th.textContent=label;hr.append(th);}head.append(hr);table.append(head);const body=document.createElement('tbody');
 for(const playerId of round.playerIds){const player=state.players.find(p=>p.id===playerId);const tr=document.createElement('tr');const title=document.createElement('th');title.scope='row';title.textContent=player.name;tr.append(title);
  for(const h of round.holes){const td=document.createElement('td');const input=document.createElement('input');input.type='number';input.inputMode='numeric';input.min='1';input.max='99';input.step='1';input.placeholder='—';input.setAttribute('aria-label',`${player.name}, hole ${h.number}, strokes`);input.dataset.player=playerId;input.dataset.hole=h.id;input.disabled=blocked;input.value=round.scores.find(s=>s.playerId===playerId&&s.holeId===h.id)?.strokes??'';
   input.addEventListener('change',async()=>{const raw=input.value.trim();const strokes=raw===''?null:Number(raw);if(input.validity.badInput||(strokes!==null&&(!Number.isInteger(strokes)||strokes<1||strokes>99))){input.classList.add('invalid');input.setAttribute('aria-invalid','true');notice('Enter whole strokes from 1 to 99, or clear the field for an unplayed hole.');return;}
    try{await commit('score.set',{playerId,holeId:h.id,strokes});input.classList.remove('invalid');input.removeAttribute('aria-invalid');notice('');updateTotals();renderPlayers();announce(`${player.name}, hole ${h.number}: ${strokes===null?'score cleared':strokes+' strokes'}.`);}catch{input.value=activeRound(state).scores.find(s=>s.playerId===playerId&&s.holeId===h.id)?.strokes??'';}
   });td.append(input);tr.append(td);
  }
  const total=document.createElement('td');total.className='total-cell';total.dataset.total=playerId;tr.append(total);body.append(tr);
 }table.append(body);updateTotals();
}
function updateTotals(){for(const cell of document.querySelectorAll('[data-total]')){const summary=strokeSummary(activeRound(state),cell.dataset.total);cell.textContent=summary.total??'—';const small=document.createElement('small');small.textContent=`${summary.played}/${summary.holes} holes`+(summary.played&&!summary.complete?' · partial':'');cell.append(small);}}
function renderHistory(){const round=activeRound(state);const entries=round.challenges.slice().reverse();$('historyEmpty').hidden=!!entries.length;$('historyList').replaceChildren(...entries.slice(0,30).map((entry,i)=>{const li=document.createElement('li');li.className='history-item';const num=document.createElement('span');num.className='history-number';num.textContent=String(entries.length-i).padStart(2,'0');const who=document.createElement('span');who.className='history-person';who.textContent=state.players.find(p=>p.id===entry.playerId)?.name??'Free play';const detail=document.createElement('small');detail.textContent='Hole '+round.holes.find(h=>h.id===entry.holeId).number+' · '+levelName(entry.experience).toLowerCase();who.append(detail);const chips=document.createElement('span');chips.className='history-challenge';for(const value of [entry.disc,entry.stability,entry.shot]){const chip=document.createElement('span');chip.className='challenge-chip';chip.textContent=value;chips.append(chip);}li.append(num,who,chips);return li;}));}
function render(){renderMachine();renderPlayers();renderScores();renderHistory();renderRoundPicker();}
async function choose(value){if(!inProgress())return;stopTimer();$('mainAction').disabled=true;for(const b of $('wildOptions').querySelectorAll('button'))b.disabled=true;try{await commit('challenge.choose',{value});index=0;if(inProgress()&&!state.draft.wildcard)startTimer();render();const d=state.draft;if(d.stage==='complete'){announce(`Challenge locked: ${d.disc}, ${d.stability}, ${d.shot}.`);$('gameDisplay').classList.add('celebrate');setTimeout(()=>$('gameDisplay').classList.remove('celebrate'),550);$('mainAction').focus();}else if(d.wildcard){announce('Wild card. Choose your '+d.stage+'.');$('wildOptions').querySelector('button')?.focus();}else{announce(value+' locked. Stop the '+d.stage+' reel next.');$('mainAction').focus();}}catch(error){renderMachine();}}
$('mainAction').addEventListener('click',async()=>{if(blocked)return;try{if(rolling){const value=poolFor(state.draft.stage,state.preferences.experience)[index];await choose(value);}else if(inProgress()){index=0;startTimer();renderMachine();announce('Reel resumed.');}else{$('mainAction').disabled=true;await commit('challenge.start');index=0;startTimer();render();announce('Disc reel started. Tap to stop.');}}catch{renderMachine();}});
$('difficulty').addEventListener('input',()=>{$('difficultyName').textContent=levelName(Number($('difficulty').value));});
$('difficulty').addEventListener('change',async()=>{const experience=Number($('difficulty').value);const wasRolling=rolling;stopTimer();$('mainAction').disabled=true;try{await commit('difficulty.set',{experience});if(inProgress()&&!state.draft.wildcard)index=normalizeIndex(index,poolFor(state.draft.stage,experience).length);if(wasRolling)startTimer();renderMachine();}catch{renderMachine();}});
$('playerForm').addEventListener('submit',async event=>{event.preventDefault();const name=$('playerName').value;$('playerError').hidden=true;try{const next=applyCommand(state,'player.add',{name});void next;await commit('player.add',{name});$('playerName').value='';render();$('playerName').focus();announce(name.trim()+' added.');}catch(error){$('playerError').textContent=error.message;$('playerError').hidden=false;}});
$('activeHole').addEventListener('change',async()=>{try{await commit('hole.select',{holeId:$('activeHole').value});render();}catch{renderMachine();}});
$('newNightButton').addEventListener('click',()=>$('newNightDialog').showModal());$('cancelNight').addEventListener('click',()=>$('newNightDialog').close());$('confirmNight').addEventListener('click',async()=>{try{await commit('round.start',{holeCount:Number($('newRoundHoles').value)});$('newNightDialog').close();render();announce('New round ready.');}catch{}});
function renderRoundPicker(){let select=$('roundPicker');if(!select){const label=document.createElement('label');label.className='round-selector';label.textContent='ROUND ';select=document.createElement('select');select.id='roundPicker';select.setAttribute('aria-label','View saved round');label.append(select);$('scoreDescription').after(label);select.addEventListener('change',async()=>{stopTimer();try{await commit('round.select',{roundId:select.value});render();}catch{render();}});}select.replaceChildren(...state.rounds.map((r,i)=>{const option=document.createElement('option');option.value=r.id;option.textContent=String(i+1)+' · '+r.holes.length+' holes';return option}));select.value=state.activeRoundId;select.disabled=!!inProgress()||blocked;}
$('exportButton').addEventListener('click',()=>{let content;try{content=blocked?(repo?.raw()??'No readable stored data'):JSON.stringify({format:'disc-roller-backup',exportedAt:new Date().toISOString(),state},null,2);}catch{notice('Browser storage could not be read for export.');return;}const url=URL.createObjectURL(new Blob([content],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='disc-roller-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
function connection(){$('connectionStatus').textContent=navigator.onLine?'LOCAL PLAY':'OFFLINE PLAY';}window.addEventListener('online',connection);window.addEventListener('offline',connection);
window.addEventListener('storage',event=>{if(event.key!==STORAGE_KEY)return;stopTimer();blocked=true;notice('This round changed in another tab. Reload to continue with the latest saved scores.');render();});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&rolling){stopTimer();renderMachine();}});
render();connection();
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').then(async registration=>{await navigator.serviceWorker.ready;$('offlineStatus').textContent='Ready for offline play';registration.addEventListener('updatefound',()=>{const worker=registration.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller)$('offlineStatus').textContent='Update ready · close all app tabs to apply';});});}).catch(()=>{$('offlineStatus').textContent='Offline setup unavailable · keep this tab open';});else $('offlineStatus').textContent='Offline setup unavailable in this browser';
