import {createRequire} from 'node:module';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE||'playwright');const base=process.env.TEST_URL||'http://127.0.0.1:4176';const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});const report={base,passed:false,errors:[],checks:[]};
const saved=p=>p.evaluate(()=>JSON.parse(localStorage.getItem('disc-roller.league.v1')));
const idle=p=>p.waitForFunction(()=>document.querySelector('#saveStatus').textContent.startsWith('Saved'));
async function setup(count=4){const c=await browser.newContext({viewport:{width:320,height:480},isMobile:true,hasTouch:true});const p=await c.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto(base+'/#play');await p.evaluate(async count=>{const m=await import('./model.js');let s=m.freshState();for(let i=1;i<=count;i++)s=m.applyCommand(s,'player.add',{name:'Player '+i});localStorage.setItem(m.STORAGE_KEY,JSON.stringify(s));},count);await p.reload();await p.locator('#openScores').tap();return p;}
try{
 const p=await setup(8);assert.equal(await p.locator('#saveHole').count(),0);assert.ok(await p.locator('#previousScoreHole').isDisabled());assert.equal((await saved(p)).rounds[0].scores.length,0);
 await p.evaluate(()=>{const request=navigator.locks.request.bind(navigator.locks);navigator.locks.request=(name,callback)=>request(name,async lock=>{await new Promise(r=>setTimeout(r,30));return callback(lock);});const plus=document.querySelector('.score-stepper button:last-child');for(let i=0;i<7;i++)plus.click();});assert.equal(await p.locator('.stroke-value').first().innerText(),'7');await p.locator('#nextScoreHole').tap();await p.waitForFunction(()=>document.querySelector('#quickHoleLabel').textContent==='Hole 2');let s=await saved(p);assert.equal(s.rounds[0].scores.length,1);assert.equal(s.rounds[0].scores[0].strokes,7);assert.equal(s.activeHoleId,s.rounds[0].holes[0].id);assert.match(await p.locator('#saveStatus').innerText(),/needs scores/);assert.deepEqual(await p.locator('.stroke-value').allTextContents(),Array(8).fill('—'));await p.locator('#previousScoreHole').tap();await p.waitForFunction(()=>document.querySelector('#quickHoleLabel').textContent==='Hole 1');assert.equal(await p.locator('.stroke-value').first().innerText(),'7');
 await p.getByRole('button',{name:'Decrease strokes for Player 1',exact:true}).tap();await p.locator('#scoresDialog [data-close]').tap();await idle(p);await p.reload();await p.locator('#openScores').tap();assert.equal(await p.locator('.stroke-value').first().innerText(),'6');report.checks.push('Seven queued rapid taps save before navigation; missing others stay blank; close and reload preserve correction');
 await p.evaluate(()=>{const minus=document.querySelector('.score-stepper button');for(let i=0;i<10;i++)minus.click();});await idle(p);assert.equal((await saved(p)).rounds[0].scores.length,0);assert.ok(await p.getByRole('button',{name:'Decrease strokes for Player 1',exact:true}).isDisabled());
 await p.evaluate(()=>{const plus=document.querySelector('.score-stepper button:last-child');for(let i=0;i<103;i++)plus.click();});await idle(p);assert.equal(await p.locator('.stroke-value').first().innerText(),'99');assert.equal((await saved(p)).rounds[0].scores[0].strokes,99);assert.ok(await p.getByRole('button',{name:'Increase strokes for Player 1',exact:true}).isDisabled());assert.ok(await p.evaluate(()=>!document.activeElement.matches('input,textarea,[contenteditable=true]')));
 for(let i=1;i<9;i++){await p.locator('#nextScoreHole').tap();await p.waitForFunction(n=>document.querySelector('#quickHoleLabel').textContent==='Hole '+n,i+1);}assert.ok(await p.locator('#nextScoreHole').isDisabled());assert.equal((await saved(p)).rounds[0].scores.length,1);await p.context().setOffline(true);await p.getByRole('button',{name:'Increase strokes for Player 8',exact:true}).tap();await idle(p);await p.reload();await p.locator('#scoresDialog').waitFor();assert.equal(await p.locator('.stroke-value').last().innerText(),'1');assert.equal((await saved(p)).rounds[0].scores.length,2);report.checks.push('Bounds 1–99/unplayed; first/last navigation; no phantom scores; eight-player offline autosave/reload without text focus');
 const ace=await setup(4);for(let i=0;i<3;i++)await ace.getByRole('button',{name:'Increase strokes for Player 1',exact:true}).tap();await idle(ace);await ace.waitForTimeout(1400);assert.ok(await ace.locator('#aceCue').isHidden());for(let i=0;i<2;i++)await ace.getByRole('button',{name:'Decrease strokes for Player 1',exact:true}).tap();await ace.locator('#aceCue').waitFor();await ace.waitForTimeout(4100);await ace.reload();assert.ok(await ace.locator('#aceCue').isHidden());report.checks.push('Passing through 1 does not celebrate; settled saved ace celebrates once and does not replay on reload');
 const failure=await setup();await failure.getByRole('button',{name:'Increase strokes for Player 1',exact:true}).tap();await idle(failure);const before=await failure.evaluate(()=>localStorage.getItem('disc-roller.league.v1'));await failure.evaluate(()=>{const old=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key==='disc-roller.league.v1')throw new DOMException('full','QuotaExceededError');return old.call(this,key,value);};});await failure.getByRole('button',{name:'Increase strokes for Player 1',exact:true}).tap();await failure.waitForFunction(()=>document.querySelector('#saveStatus').textContent.startsWith('Not saved'));assert.equal(await failure.evaluate(()=>localStorage.getItem('disc-roller.league.v1')),before);assert.equal(await failure.locator('.stroke-value').first().innerText(),'1');assert.ok(await failure.getByRole('button',{name:'Increase strokes for Player 1',exact:true}).isDisabled());
 const stale=await setup();const other=await stale.context().newPage();await other.goto(base+'/#play');await other.locator('#openScores').tap();await other.getByRole('button',{name:'Increase strokes for Player 1',exact:true}).tap();await idle(other);await stale.waitForFunction(()=>document.querySelector('.score-stepper button:last-child').disabled);await stale.getByRole('button',{name:'Increase strokes for Player 1',exact:true}).dispatchEvent('click');assert.equal((await saved(stale)).rounds[0].scores[0].strokes,1);report.checks.push('Storage failure restores last saved value with honest error and blocks editing; stale tab cannot overwrite');
 assert.deepEqual(report.errors,[]);report.passed=true;
}finally{await fs.writeFile('review/autosave-results.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));await browser.close();}
