import {createRequire} from 'node:module';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const base=(process.env.TEST_URL||'http://127.0.0.1:4173').replace(/\/$/,'');
const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
const output={browser:browser.version(),base,checks:[],errors:[],externalRequests:[],layouts:[]};
await fs.mkdir('review',{recursive:true});
const contexts=[];
async function context(options={}){const c=await browser.newContext({viewport:{width:390,height:740},reducedMotion:'reduce',...options});contexts.push(c);return c;}
async function waitLabel(p,label){await p.waitForFunction(label=>document.querySelector('#actionLabel').textContent===label,label);}
async function close(p){await p.locator('dialog[open] .close-button').click();await p.waitForFunction(()=>!document.querySelector('dialog[open]'));}
async function complete(p){for(let i=0;i<8;i++){await p.waitForFunction(()=>!document.querySelector('#mainAction').disabled||!document.querySelector('#wildDisplay').hidden);if(await p.locator('#completeDisplay').isVisible())return;if(await p.locator('#wildDisplay').isVisible())await p.locator('#wildOptions button').first().click();else await p.locator('#mainAction').click();await p.waitForTimeout(85);}assert.ok(await p.locator('#completeDisplay').isVisible(),'Challenge completed');}
async function fit(p,label){const v=await p.evaluate(()=>{const box=document.querySelector('#gameDisplay');return {width:innerWidth,height:innerHeight,scrollWidth:document.documentElement.scrollWidth,scrollHeight:document.documentElement.scrollHeight,displayHeight:box.clientHeight,displayScroll:box.scrollHeight,button:document.querySelector('#mainAction').getBoundingClientRect().toJSON(),font:parseFloat(getComputedStyle(document.querySelector('#reelText')).fontSize)}});output.layouts.push({label,...v});assert.ok(v.scrollWidth<=v.width,JSON.stringify(v));assert.ok(v.scrollHeight<=v.height+1,JSON.stringify(v));assert.ok(v.displayScroll<=v.displayHeight+2,`Clipped display ${label}: ${JSON.stringify(v)}`);if(await p.locator('#mainAction').isVisible()){assert.ok(v.button.height>=68);assert.ok(v.button.bottom<=v.height);}assert.ok(v.font>=30);}
async function run(){
 const c=await context();const p=await c.newPage();p.on('pageerror',e=>output.errors.push(e.message));p.on('request',r=>{if(new URL(r.url()).origin!==new URL(base).origin)output.externalRequests.push(r.url())});await p.goto(base);await p.evaluate(()=>document.fonts.ready);
 assert.ok(await p.locator('#splashScreen').isVisible());assert.equal(await p.locator('dialog[open]').count(),0);assert.equal(await p.evaluate(()=>localStorage.getItem('disc-roller.league.v1')),null);
 await p.screenshot({path:'review/simple-splash.png'});await p.locator('#startButton').click();assert.ok(await p.locator('#rollerScreen').isVisible());assert.equal(await p.locator('dialog[open]').count(),0);assert.equal(await p.locator('#actionLabel').innerText(),'ROLL');await p.locator('#mainAction').click();await waitLabel(p,'STOP');assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('disc-roller.league.v1')).players.length),0);
 output.checks.push('Fresh browser: splash Start opens playable roller, no setup/players/tutorial gate');
 await p.locator('#openHelp').click();assert.ok(await p.locator('#helpDialog').isVisible());const locked=await p.locator('#reelText').innerText();await p.waitForTimeout(180);assert.equal(await p.locator('#reelText').innerText(),locked);await p.keyboard.press('Tab');assert.ok(await p.evaluate(()=>!!document.activeElement.closest('dialog[open]')));await p.keyboard.press('Escape');await p.waitForFunction(()=>!document.querySelector('dialog[open]'));await waitLabel(p,'RESUME');assert.equal(await p.evaluate(()=>document.activeElement.id),'openHelp');
 for(let i=0;i<3;i++){await p.locator('#openScores').click();await p.goBack();await p.waitForFunction(()=>!document.querySelector('dialog[open]'));assert.ok(await p.locator('#rollerScreen').isVisible());}
 await p.locator('#openPlayers').click();await p.reload();assert.ok(await p.locator('#playersDialog').isVisible());await close(p);await waitLabel(p,'RESUME');
 output.checks.push('Menus pause; native focus containment; Escape, Close, repeated browser Back and modal reload');
 await p.locator('#mainAction').click();await waitLabel(p,'STOP');await p.locator('#openHelp').click();await close(p);await p.screenshot({path:'review/simple-roller-mobile.png'});await p.locator('#mainAction').click();await waitLabel(p,'STOP');await complete(p);
 assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('disc-roller.league.v1')).rounds[0].challenges.length),1);await p.screenshot({path:'review/simple-locked-mobile.png'});
 output.checks.push('Timing stops, wildcard branch where reached, and locked challenge');
 await p.locator('#openPlayers').click();for(const name of ['Alex','Taylor']){await p.getByLabel('Player name',{exact:true}).fill(name);await p.getByRole('button',{name:'Add player',exact:true}).click();await p.locator('.player-name').filter({hasText:name}).waitFor();}await close(p);
 await p.locator('#openScores').click();const score=()=>p.getByRole('spinbutton',{name:'Alex, hole 1, strokes',exact:true});await score().fill('4');await score().press('Tab');await p.waitForFunction(()=>document.querySelector('[data-total] b')?.textContent==='4');await score().fill('3');await score().press('Tab');await p.waitForFunction(()=>document.querySelector('[data-total] b')?.textContent==='3');await p.getByRole('button',{name:'Increase strokes for Taylor',exact:true}).click();await p.waitForFunction(()=>[...document.querySelectorAll('[data-total] b')][1]?.textContent==='1');await p.screenshot({path:'review/simple-scores-mobile.png'});
 await p.reload();assert.ok(await p.locator('#scoresDialog').isVisible());assert.equal(await score().inputValue(),'3');await p.locator('#nextScoreHole').click();const hole2=p.getByRole('spinbutton',{name:'Alex, hole 2, strokes',exact:true});await hole2.fill('5');await hole2.press('Tab');await p.waitForFunction(()=>document.querySelector('[data-total] b')?.textContent==='8');await hole2.fill('');await hole2.press('Tab');await p.waitForFunction(()=>document.querySelector('[data-total] b')?.textContent==='3');
 output.checks.push('Opt-in player setup; large per-hole stroke controls, correction, blank clearing and totals');
 await close(p);await p.locator('#openPlayers').click();await p.locator('#newNightButton').click();assert.ok(await p.locator('#newNightDialog').isVisible());await p.keyboard.press('Escape');await p.waitForFunction(()=>document.querySelector('#playersDialog').open);await p.locator('#newNightButton').click();await p.locator('#newRoundHoles').selectOption('18');await p.locator('#confirmNight').click();await p.waitForFunction(()=>document.querySelector('#playersDialog').open);await p.waitForFunction(()=>document.querySelector('#roundPicker').selectedOptions[0].textContent.includes('18'));await p.locator('#roundPicker').selectOption({index:0});await p.waitForFunction(()=>document.querySelector('#roundPicker').selectedOptions[0].textContent.includes('9'));await close(p);await p.locator('#openScores').click();assert.equal(await score().inputValue(),'3');await close(p);
 output.checks.push('Nested new-round dialog Back/Escape; 18-hole round and archived score preservation');
 await p.waitForFunction(()=>navigator.serviceWorker.controller);await c.setOffline(true);await p.reload();assert.ok(await p.locator('#rollerScreen').isVisible());await p.locator('#openScores').click();assert.equal(await score().inputValue(),'3');await score().fill('6');await score().press('Tab');await p.waitForFunction(()=>document.querySelector('[data-total] b')?.textContent==='6');await p.reload();assert.equal(await score().inputValue(),'6');await close(p);await c.setOffline(false);
 output.checks.push('Offline screen reload, saved scores and offline edits');
 await p.locator('#mainAction').click();await waitLabel(p,'STOP');await p.reload();await waitLabel(p,'RESUME');await p.locator('#openPlayers').click();await p.locator('#difficulty').fill('100');await p.locator('#difficulty').dispatchEvent('change');await p.waitForFunction(()=>JSON.parse(localStorage.getItem('disc-roller.league.v1')).preferences.experience===100);await close(p);await waitLabel(p,'RESUME');await p.locator('#mainAction').click();await complete(p);
 output.checks.push('Interrupted challenge refresh/resume; optional difficulty change remains safe');
 await p.locator('#openPlayers').click();await p.getByLabel('Player name',{exact:true}).fill('<img src=x onerror=alert(1)>');await p.getByRole('button',{name:'Add player',exact:true}).click();await p.locator('.player-name').filter({hasText:'<img src=x onerror=alert(1)>'}).waitFor();assert.equal(await p.locator('.player-list img').count(),0);await close(p);
 output.checks.push('HTML-like names remain text');
 // Seed only isolated test contexts to exercise the longest labels and all layouts.
 const layoutContext=await context();const lp=await layoutContext.newPage();await lp.goto(base+'/#play');await lp.evaluate(async()=>{const m=await import('./model.js');let s=m.freshState();s=m.applyCommand(s,'difficulty.set',{experience:100});s=m.applyCommand(s,'challenge.start');s=m.applyCommand(s,'challenge.choose',{value:'Fairway Driver'});localStorage.setItem(m.STORAGE_KEY,JSON.stringify(s));});
 for(const [width,height] of [[320,480],[320,568],[390,664],[390,844],[667,375],[1280,800]]){await lp.setViewportSize({width,height});await lp.reload();await fit(lp,'paused-stability');await lp.locator('#mainAction').click();await waitLabel(lp,'STOP');await lp.locator('#openHelp').click();await close(lp);await fit(lp,'menu-return');}
 await lp.evaluate(async()=>{const m=await import('./model.js');let s=m.freshState();s=m.applyCommand(s,'challenge.start');for(const value of ['Fairway Driver','WILDCARD','Super Understable','WILDCARD'])s=m.applyCommand(s,'challenge.choose',{value});localStorage.setItem(m.STORAGE_KEY,JSON.stringify(s));});
 for(const [width,height] of [[320,480],[320,568],[390,664],[667,375]]){await lp.setViewportSize({width,height});await lp.reload();await fit(lp,'eight-choice-wildcard');}
 await lp.setViewportSize({width:390,height:740});await lp.reload();await lp.screenshot({path:'review/simple-wildcard-mobile.png'});await lp.locator('#wildOptions button').filter({hasText:'Backhand'}).click();await lp.waitForFunction(()=>document.querySelector('#completeDisplay').hidden===false);await lp.setViewportSize({width:320,height:480});await fit(lp,'long-label-completed');await lp.setViewportSize({width:1280,height:800});await lp.screenshot({path:'review/simple-desktop.png'});
 output.checks.push('Viewport fit at 320px, reduced browser-chrome heights, landscape; long labels and eight wildcards');
 const p2=await c.newPage();await p2.goto(base+'/#play');await p2.locator('#openScores').click();await p2.getByRole('spinbutton',{name:'Alex, hole 1, strokes',exact:true}).fill('7');await p2.getByRole('spinbutton',{name:'Alex, hole 1, strokes',exact:true}).press('Tab');await p.waitForFunction(()=>document.querySelector('#notice').textContent.includes('another tab'));assert.ok(await p.locator('#mainAction').isDisabled());
 const corrupt=await context();await corrupt.addInitScript(()=>localStorage.setItem('disc-roller.league.v1','corrupt-test'));const cp=await corrupt.newPage();await cp.goto(base+'/#play');assert.ok(await cp.locator('#mainAction').isDisabled());await cp.locator('#openScores').click();assert.ok(await cp.locator('#exportButton').isEnabled());assert.equal(await cp.evaluate(()=>localStorage.getItem('disc-roller.league.v1')),'corrupt-test');
 output.checks.push('Other-tab edits block stale writes; corrupt data preserved with backup access');
 assert.deepEqual(output.errors,[]);assert.deepEqual(output.externalRequests,[]);
}
try{await run();output.passed=true;}catch(error){output.passed=false;output.failure=error.stack;throw error;}finally{await fs.writeFile('review/browser-results.json',JSON.stringify(output,null,2));console.log(JSON.stringify(output,null,2));for(const c of contexts)await c.close();await browser.close();}
