import test from 'node:test';import assert from 'node:assert/strict';
import {strokeSummary,freshState,applyCommand,activeRound,teeOrder,remainingPlayers,scoreResult,LocalRepository,STORAGE_KEY,PLAYER_COLORS,validateState} from '../model.js';
const card=()=>['A','B','C','D'].reduce((s,name)=>applyCommand(s,'player.add',{name}),freshState());
const scores=(s,holeIndex,values)=>applyCommand(s,'score.hole.set',{holeId:activeRound(s).holes[holeIndex].id,scores:s.players.map((p,i)=>({playerId:p.id,strokes:values[i]}))});
test('every player has a distinct stable color through rounds and reloads',()=>{let s=card();for(let i=4;i<24;i++)s=applyCommand(s,'player.add',{name:'Player '+i});assert.equal(new Set(s.players.map(p=>PLAYER_COLORS[p.colorIndex])).size,24);const colors=s.players.map(p=>p.colorIndex);s=applyCommand(s,'round.start',{holeCount:18});assert.deepEqual(validateState(JSON.parse(JSON.stringify(s))).players.map(p=>p.colorIndex),colors);});
test('honors use previous hole, retain tied earlier honors, never cumulative total',()=>{let s=card();const [a,b,c,d]=s.players.map(p=>p.id);let r=activeRound(s);assert.deepEqual(teeOrder(r,r.holes[0].id).order,[a,b,c,d]);s=scores(s,0,[4,2,3,3]);s=applyCommand(s,'hole.advance');assert.equal(s.activePlayerId,b);assert.deepEqual(teeOrder(activeRound(s),s.activeHoleId).order,[b,c,d,a]);s=scores(s,1,[3,3,3,3]);s=applyCommand(s,'hole.advance');assert.deepEqual(teeOrder(activeRound(s),s.activeHoleId).order,[b,c,d,a]);s=scores(s,2,[2,4,3,3]);s=applyCommand(s,'hole.advance');assert.deepEqual(teeOrder(activeRound(s),s.activeHoleId).order,[a,c,d,b]);assert.equal(s.activePlayerId,a);});
test('missing scores block next hole and never act like zero',()=>{let s=card();s=scores(s,0,[2,null,3,4]);const order=teeOrder(activeRound(s),activeRound(s).holes[1].id);assert.equal(order.ready,false);assert.equal(order.missingHole,1);assert.throws(()=>applyCommand(s,'hole.advance'),/every score/);assert.throws(()=>applyCommand(s,'hole.select',{holeId:activeRound(s).holes[1].id}),/every score/);assert.equal(activeRound(s).scores.length,3);});
test('explicit handoff finds every remaining player; incomplete challenge cannot be skipped',()=>{let s=card();for(const p of s.players){assert.equal(s.activePlayerId,p.id);s=applyCommand(s,'challenge.start');assert.throws(()=>applyCommand(s,'turn.next'));for(const value of ['Putter','Neutral','Backhand'])s=applyCommand(s,'challenge.choose',{value});if(p.id!==s.players.at(-1).id)s=applyCommand(s,'turn.next');}assert.deepEqual(remainingPlayers(activeRound(s),s.activeHoleId),[]);assert.throws(()=>applyCommand(s,'turn.next'));});
test('par defaults to 3; override never invents or changes a stroke',()=>{let s=card();assert.ok(activeRound(s).holes.every(h=>h.par===3));s=scores(s,0,[1,2,3,4]);const before=structuredClone(activeRound(s).scores);s=applyCommand(s,'par.set',{holeId:s.activeHoleId,par:4});assert.equal(activeRound(s).holes[0].par,4);assert.deepEqual(activeRound(s).scores,before);for(const par of [0,1,10,2.5,NaN])assert.throws(()=>applyCommand(s,'par.set',{holeId:s.activeHoleId,par}));});
test('score symbols classify ace, birdie, par, bogey and double or worse',()=>{assert.equal(scoreResult(null,3),'unplayed');assert.equal(scoreResult(1,3),'ace');assert.equal(scoreResult(2,3),'birdie');assert.equal(scoreResult(3,3),'par');assert.equal(scoreResult(4,3),'bogey');assert.equal(scoreResult(5,3),'double-bogey');assert.equal(scoreResult(9,3),'double-bogey');assert.equal(scoreResult(2,4),'under-par');});
test('schema 1 migration is read-only until save and retains a byte-exact original backup',()=>{let legacy=scores(card(),0,[2,null,3,4]);legacy.schemaVersion=1;legacy.players.forEach(p=>delete p.colorIndex);legacy.rounds.forEach(r=>{delete r.teeOrders;r.holes.forEach(h=>h.par=null)});const raw=JSON.stringify(legacy);const store=new Map([[STORAGE_KEY,raw]]);const repo=new LocalRepository({getItem:k=>store.get(k)??null,setItem:(k,v)=>store.set(k,v)});const migrated=repo.load();assert.equal(migrated.schemaVersion,2);assert.equal(store.get(STORAGE_KEY),raw);assert.deepEqual(migrated.rounds[0].scores,legacy.rounds[0].scores);assert.equal(migrated.rounds[0].scores.length,3);assert.ok(migrated.rounds[0].holes.every(h=>h.par===3));repo.save(applyCommand(migrated,'par.set',{holeId:migrated.activeHoleId,par:4}),migrated.revision);assert.equal(store.get(STORAGE_KEY+'.pre-v2'),raw);assert.equal(repo.load().rounds[0].holes[0].par,4);});
test('already established honors survive corrections to earlier played holes',()=>{let s=scores(card(),0,[4,2,3,3]);s=applyCommand(s,'hole.advance');const order=teeOrder(activeRound(s),s.activeHoleId).order;s=scores(s,0,[2,4,3,3]);assert.deepEqual(teeOrder(activeRound(s),s.activeHoleId).order,order);});

test('relative par counts only scored holes and follows edits and clearing',()=>{let s=card(),r=activeRound(s),id=s.players[0].id;assert.equal(strokeSummary(r,id).toPar,null);s=scores(s,0,[2,null,null,null]);s=scores(s,1,[4,null,null,null]);assert.equal(strokeSummary(activeRound(s),id).toPar,0);s=applyCommand(s,'par.set',{holeId:r.holes[1].id,par:4});assert.equal(strokeSummary(activeRound(s),id).toPar,-1);s=applyCommand(s,'par.set',{holeId:r.holes[8].id,par:9});assert.equal(strokeSummary(activeRound(s),id).toPar,-1);s=scores(s,0,[null,null,null,null]);assert.equal(strokeSummary(activeRound(s),id).total,4);assert.equal(strokeSummary(activeRound(s),id).toPar,0);});
