import {createRequire} from 'node:module';import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE||'playwright');const base=process.env.TEST_URL||'http://127.0.0.1:4176';const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
const report={base,checks:[],errors:[],layouts:[]};await fs.mkdir('review',{recursive:true});
async function page(options={}){const c=await browser.newContext({viewport:{width:390,height:740},isMobile:true,hasTouch:true,colorScheme:'light',...options});const p=await c.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto(base+'/#play');return p;}
const saved=p=>p.evaluate(()=>JSON.parse(localStorage.getItem('disc-roller.league.v1')));
async function close(p){await p.locator('dialog[open] .close-button').tap();await p.waitForFunction(()=>!document.querySelector('dialog[open]'));}
async function waitIdle(p){await p.waitForFunction(()=>!document.querySelector('#mainAction').disabled);}
async function stage(p){const before=(await saved(p))?.draft?.stage??'disc';await p.locator('#mainAction').tap();await p.waitForFunction(()=>document.querySelector('#actionLabel').textContent==='QUICK STOP');await p.waitForTimeout(70);await p.locator('#mainAction').tap();await p.waitForTimeout(620);if(await p.locator('#wildDisplay').isVisible())await p.locator('#wildOptions button').first().tap();await p.waitForFunction(before=>JSON.parse(localStorage.getItem('disc-roller.league.v1')).draft.stage!==before,before);await waitIdle(p);assert.equal((await saved(p)).draft.spin,null);}
async function wheels(p,values){for(let i=0;i<values.length;i++)await p.locator('.compact-wheel').nth(i).evaluate((e,v)=>{e.scrollLeft=(v??0)*44;e.dispatchEvent(new Event('scroll'));},values[i]);}
async function save(p){await p.locator('#saveHole').tap();await p.waitForFunction(()=>!document.querySelector('#saveHole').disabled&&!document.querySelector('#saveStatus').textContent.includes('Not saved'));}
async function fitEntry(p,label){const v=await p.evaluate(()=>{const d=document.querySelector('#scoresDialog'),footer=document.querySelector('.quick-footer').getBoundingClientRect();return{w:innerWidth,h:innerHeight,bodyW:document.documentElement.scrollWidth,dialogW:d.scrollWidth,client:d.clientWidth,footer:footer.top,rows:[...document.querySelectorAll('.quick-player')].slice(0,4).map(e=>({top:e.getBoundingClientRect().top,bottom:e.getBoundingClientRect().bottom})),inputs:d.querySelectorAll('input,textarea,[contenteditable=true]').length};});assert.ok(v.bodyW<=v.w&&v.dialogW<=v.client,JSON.stringify(v));assert.ok(v.rows.length===4&&v.rows.every(r=>r.bottom<=v.footer+1),JSON.stringify(v));assert.equal(v.inputs,0);report.layouts.push({label,...v});}
try{
 const p=await page();assert.equal(await p.locator('#actionLabel').innerText(),'BEGIN DISC');await p.locator('#openPlayers').tap();for(const name of ['Avery','Blake','Casey','Devon']){await p.locator('#playerName').fill(name);await p.getByRole('button',{name:'Add player',exact:true}).tap();await p.locator('.player-name').filter({hasText:name}).waitFor();}await close(p);assert.equal(await p.locator('#currentPlayerLabel').innerText(),'Avery');assert.equal(new Set((await saved(p)).players.map(p=>p.colorIndex)).size,4);
 await p.locator('#mainAction').tap();await p.waitForFunction(()=>document.querySelector('#actionLabel').textContent==='QUICK STOP');await p.waitForTimeout(1400);assert.equal(await p.locator('#actionLabel').innerText(),'LET IT SPIN');await p.evaluate(()=>document.querySelector('#mainAction').dispatchEvent(new MouseEvent('click',{bubbles:true})));assert.equal((await saved(p)).draft.stage,'disc');await p.waitForFunction(()=>document.querySelector('#actionLabel').textContent==='BEGIN STABILITY');const afterDisc=await saved(p);await p.waitForTimeout(1600);assert.equal((await saved(p)).revision,afterDisc.revision);assert.equal((await saved(p)).draft.spin,null);
 await stage(p);assert.equal(await p.locator('#actionLabel').innerText(),'BEGIN SHOT');await stage(p);assert.equal(await p.locator('#actionLabel').innerText(),'PASS TO Blake');
 for(const name of ['Blake','Casey','Devon']){await p.locator('#mainAction').tap();await p.waitForFunction(name=>document.querySelector('#currentPlayerLabel').textContent===name,name);assert.equal(await p.locator('#actionLabel').innerText(),'BEGIN DISC');for(let i=0;i<3;i++)await stage(p);}
 assert.equal(await p.locator('#actionLabel').innerText(),'SCORE HOLE');assert.equal((await saved(p)).rounds[0].challenges.length,4);report.checks.push('Every section requires a new Begin; automatic stop cannot chain; late Quick Stop rejected; explicit named handoff reaches all four players');
 await p.locator('#mainAction').tap();await p.waitForFunction(()=>document.querySelector('#scoresDialog').open);await fitEntry(p,'390 day');await p.setViewportSize({width:320,height:480});await fitEntry(p,'320 day');await p.screenshot({path:'review/course-day-scores-320.png'});
 await wheels(p,[3,2,3,null]);await save(p);assert.ok(await p.locator('#advanceHole').isDisabled());await wheels(p,[3,2,3,3]);await save(p);assert.ok(await p.locator('#advanceHole').isEnabled());await p.locator('#advanceHole').tap();await p.waitForFunction(()=>!document.querySelector('dialog[open]'));assert.equal(await p.locator('#currentPlayerLabel').innerText(),'Blake');const onHole2=await saved(p);assert.equal(onHole2.rounds[0].holes.find(h=>h.id===onHole2.activeHoleId).number,2);
 await p.locator('#openScores').tap();await wheels(p,[3,3,3,3]);await save(p);await p.locator('#advanceHole').tap();await p.waitForFunction(()=>!document.querySelector('dialog[open]'));assert.equal(await p.locator('#currentPlayerLabel').innerText(),'Blake');report.checks.push('Missing score blocks next hole; Blake birdies hole 1 and retains honors on hole 3 after tied pars on hole 2');
 await p.setViewportSize({width:390,height:740});await p.locator('#rollerScreen [data-theme-toggle]').tap();await p.screenshot({path:'review/course-night-player.png'});await p.locator('#openScores').tap();await fitEntry(p,'390 night');await wheels(p,[1,2,5,6]);await p.locator('#parButton').tap();await p.getByRole('button',{name:'Set par 4',exact:true}).tap();await p.waitForFunction(()=>document.querySelector('#scoresDialog').open);assert.equal(await p.locator('#parButton').innerText(),'Par 4 ✎');assert.equal(await p.locator('.compact-wheel').first().getAttribute('data-value'),'1');await save(p);assert.ok(await p.locator('#aceCue').isVisible());await p.emulateMedia({reducedMotion:'reduce'});assert.equal(await p.locator('#aceCue').evaluate(e=>getComputedStyle(e).animationName),'none');await p.waitForTimeout(750);await p.screenshot({path:'review/course-night-ace.png'});await p.waitForTimeout(4100);assert.ok(await p.locator('#aceCue').isHidden());await save(p);assert.ok(await p.locator('#aceCue').isHidden());
 await p.locator('#openScorecard').tap();await p.waitForFunction(()=>document.querySelector('#scorecardDialog').open);assert.ok(await p.locator('#scoreGrid .ace').count());assert.ok(await p.locator('#scoreGrid .birdie').count());assert.ok(await p.locator('#scoreGrid .under-par').count());assert.ok(await p.locator('#scoreGrid .par').count());assert.ok(await p.locator('#scoreGrid .bogey').count());assert.ok(await p.locator('#scoreGrid .double-bogey').count());assert.notEqual(await p.locator('#scoreGrid .bogey span').first().evaluate(e=>getComputedStyle(e).backgroundColor),await p.locator('#scoreGrid .double-bogey span').first().evaluate(e=>getComputedStyle(e).backgroundColor));await p.screenshot({path:'review/course-night-card.png'});await p.reload();assert.ok(await p.locator('#scorecardDialog').isVisible());assert.ok(await p.locator('#aceCue').isHidden());assert.equal((await saved(p)).rounds[0].holes[2].par,4);report.checks.push('Par editor retains unsaved wheel choices; confirmed ace cue occurs once; full card is separate and accessible score shapes survive reload');
 const many=await page();await many.evaluate(async()=>{const m=await import('./model.js');let s=m.freshState();for(let i=1;i<=8;i++)s=m.applyCommand(s,'player.add',{name:'Player '+i});localStorage.setItem(m.STORAGE_KEY,JSON.stringify(s));});await many.reload();await many.locator('#openScores').tap();await many.setViewportSize({width:320,height:480});await fitEntry(many,'8-player list, first four visible');assert.equal(await many.locator('.quick-player').count(),8);const pane=await many.locator('.quick-player-list').boundingBox();const vertical=await many.context().newCDPSession(many);const vx=Math.round(pane.x+pane.width/2),vy=Math.round(pane.y+pane.height-25);await vertical.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:vx,y:vy}]});for(let delta=10;delta<=160;delta+=10){await vertical.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:vx,y:vy-delta}]});await many.waitForTimeout(25);}await vertical.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await many.waitForTimeout(400);assert.ok(await many.locator('.quick-player-list').evaluate(e=>e.scrollTop>0),'Vertical swipe over score wheels scrolls the player list');await vertical.detach();const last=many.locator('.compact-wheel').last();await last.scrollIntoViewIfNeeded();const box=await last.boundingBox();const cd=await many.context().newCDPSession(many);const x=Math.round(box.x+box.width-20),y=Math.round(box.y+box.height/2);await cd.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});for(let delta=10;delta<=90;delta+=10){await cd.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x-delta,y}]});await many.waitForTimeout(30);}await cd.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await many.waitForTimeout(600);await cd.detach();const selected=Number(await last.getAttribute('data-value'));assert.ok(selected>0);assert.ok(await many.evaluate(()=>!document.activeElement.matches('input,textarea,[contenteditable=true]')));assert.equal((await saved(many)).rounds[0].scores.length,0);await save(many);assert.equal((await saved(many)).rounds[0].scores[0].playerId,(await saved(many)).players[7].id);assert.equal((await saved(many)).rounds[0].scores[0].strokes,selected);
 await many.context().setOffline(true);await many.reload();await many.waitForFunction(()=>document.querySelector('#scoresDialog').open);assert.equal((await saved(many)).rounds[0].scores[0].strokes,selected);assert.equal(await many.locator('.quick-player').count(),8);report.checks.push('Eight-player list scrolls within quick entry; touch swipe edits player 8 with no text-input focus; Save and offline reload preserve it');
 assert.deepEqual(report.errors,[]);report.passed=true;
}catch(e){report.passed=false;report.failure=e.stack;throw e;}finally{await fs.writeFile('review/course-browser-results.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();}
