import {createRequire} from 'node:module';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE||'playwright');const base=process.env.TEST_URL||'http://127.0.0.1:4176';const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});const report={base,passed:false,errors:[],checks:[]};
async function page(reduced=false){const c=await browser.newContext({viewport:{width:320,height:568},isMobile:true,hasTouch:true,reducedMotion:reduced?'reduce':'no-preference'});const p=await c.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto(base+'/#play');return p;}
async function shot(p){await p.evaluate(async()=>{const m=await import('./model.js');let s=m.freshState();s=m.applyCommand(s,'challenge.start');s=m.applyCommand(s,'challenge.choose',{value:'Driver'});s=m.applyCommand(s,'challenge.choose',{value:'Understable'});localStorage.setItem(m.STORAGE_KEY,JSON.stringify(s));});await p.reload();}
const idle=p=>p.waitForFunction(()=>document.querySelector('#saveStatus').textContent.startsWith('Saved'));
async function aces(p,scores){await p.evaluate(async scores=>{const m=await import('./model.js');let s=m.freshState();for(const name of ['Avery','Blake'])s=m.applyCommand(s,'player.add',{name});s=m.applyCommand(s,'score.hole.set',{holeId:s.activeHoleId,scores:s.players.map((p,i)=>({playerId:p.id,strokes:scores[i]}))});localStorage.setItem(m.STORAGE_KEY,JSON.stringify(s));},scores);await p.reload();await p.locator('#openScores').tap();}
try{
 const p=await page();await shot(p);for(const width of [320,360,390]){await p.setViewportSize({width,height:568});const text=await p.locator('#result-stability').evaluate(e=>{const r=document.createRange();r.selectNodeContents(e);const box=e.parentElement.getBoundingClientRect();return{lines:r.getClientRects().length,font:parseFloat(getComputedStyle(e).fontSize),fits:[...r.getClientRects()].every(r=>r.left>=box.left&&r.right<=box.right),text:e.textContent};});assert.equal(text.text,'Understable');assert.ok(text.font>=15&&text.fits&&text.lines===1,JSON.stringify(text));}await p.setViewportSize({width:320,height:568});await p.screenshot({path:'review/understable-320.png'});
 await p.locator('#mainAction').tap();await p.waitForFunction(()=>document.querySelector('#actionLabel').textContent==='QUICK STOP');await p.locator('#mainAction').tap();await p.waitForFunction(()=>document.querySelector('#finalRollDisplay').hidden===false);const value=await p.locator('#finalRollValue').innerText();assert.ok(value);assert.ok(await p.locator('#completeDisplay').isHidden());assert.ok(await p.locator('#mainAction').isDisabled());const before=await p.evaluate(()=>localStorage.getItem('disc-roller.league.v1'));await p.locator('#mainAction').dispatchEvent('click');assert.equal(await p.evaluate(()=>localStorage.getItem('disc-roller.league.v1')),before);await p.waitForTimeout(500);assert.ok(await p.locator('#finalRollDisplay').isVisible());await p.screenshot({path:'review/final-roll-pause.png'});await p.locator('#completeDisplay').waitFor();assert.equal(await p.locator('#finalChallenge strong').last().innerText(),value);
 const reduced=await page(true);await shot(reduced);await reduced.locator('#mainAction').tap();await reduced.waitForFunction(()=>document.querySelector('#actionLabel').textContent==='QUICK STOP');await reduced.locator('#mainAction').tap();await reduced.locator('#finalRollDisplay').waitFor();await reduced.locator('#openHelp').tap();await reduced.keyboard.press('Escape');await reduced.locator('#completeDisplay').waitFor();assert.equal(await reduced.evaluate(()=>JSON.parse(localStorage.getItem('disc-roller.league.v1')).rounds[0].challenges.length),1);await reduced.reload();assert.ok(await reduced.locator('#completeDisplay').isVisible());assert.ok(await reduced.locator('#finalRollDisplay').isHidden());report.checks.push('Understable fits at 320/360/390 with 15px+ type; final shot pauses before summary, blocks duplicate input and survives menu/reload/reduced-motion interruption');
 const ace=await page();await aces(ace,[1,1]);await ace.waitForTimeout(1400);assert.ok(await ace.locator('#aceDialog').isHidden());await ace.locator('#nextScoreHole').tap();await ace.locator('#aceDialog').waitFor();assert.equal(await ace.locator('#scoresDialog').isVisible(),false);assert.equal(await ace.locator('#rollerScreen').isVisible(),true);assert.match(await ace.locator('#acePlayers').innerText(),/Avery & Blake/);assert.match(await ace.locator('#holeLabel').innerText(),/Hole 2/);const rect=await ace.locator('#aceDialog').boundingBox();assert.ok(Math.abs(rect.y+rect.height/2-284)<3);await ace.waitForTimeout(500);await ace.screenshot({path:'review/ace-centered-320.png'});await ace.keyboard.press('Escape');assert.equal(await ace.evaluate(()=>document.activeElement.id),'mainAction');await ace.reload();assert.ok(await ace.locator('#aceDialog').isHidden());await ace.locator('#openScores').tap();await ace.locator('#previousScoreHole').tap();await ace.waitForFunction(()=>document.querySelector('#quickHoleLabel').textContent==='Hole 1');await ace.locator('#nextScoreHole').tap();await ace.waitForFunction(()=>!document.querySelector('dialog[open]'));assert.equal(await ace.evaluate(()=>JSON.parse(localStorage.getItem('disc-roller.league.v1')).rounds[0].aceCelebrations.length),2);
 const corrected=await page(true);await aces(corrected,[1,3]);await corrected.getByRole('button',{name:'Increase strokes for Avery'}).tap();await idle(corrected);await corrected.locator('#nextScoreHole').tap();await corrected.waitForFunction(()=>!document.querySelector('dialog[open]'));assert.ok(await corrected.locator('#aceDialog').isHidden());await aces(corrected,[1,3]);await corrected.locator('#nextScoreHole').tap();await corrected.locator('#aceDialog').waitFor();assert.equal(await corrected.locator('#aceDialog').evaluate(e=>getComputedStyle(e).animationName),'none');await corrected.waitForFunction(()=>!document.querySelector('#aceDialog').open,{},{timeout:6000});report.checks.push('No celebration on score edits; Next returns to roller with centered named multi-ace; receipts prevent replay; corrected-away ace excluded; Escape/focus, auto-dismiss and reduced motion work');assert.deepEqual(report.errors,[]);report.passed=true;
}finally{await fs.writeFile('review/effects-results.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));await browser.close();}
