import {createRequire} from 'node:module';import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE||'playwright');
const base=process.env.TEST_URL||'http://127.0.0.1:4175';const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
const report={checks:[],errors:[],layouts:[],base};const contexts=[];await fs.mkdir('review',{recursive:true});
async function page(options={}){const c=await browser.newContext({viewport:{width:390,height:740},colorScheme:'light',...options});contexts.push(c);const p=await c.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto(base+'/#play');return p;}
const saved=p=>p.evaluate(()=>JSON.parse(localStorage.getItem('disc-roller.league.v1')));
async function seed(p,stage='disc'){await p.evaluate(async stage=>{const m=await import('./model.js');let s=m.freshState();s=m.applyCommand(s,'challenge.start');if(stage!=='disc')s=m.applyCommand(s,'challenge.choose',{value:'Putter'});if(stage==='shot')s=m.applyCommand(s,'challenge.choose',{value:'Neutral'});localStorage.setItem(m.STORAGE_KEY,JSON.stringify(s));},stage);await p.reload();}
async function start(p){await p.locator('#mainAction').click();await p.waitForFunction(()=>document.querySelector('#actionLabel').textContent==='QUICK STOP');}
async function fit(p,description){const result=await p.evaluate(()=>({w:innerWidth,h:innerHeight,sw:document.documentElement.scrollWidth,sh:document.documentElement.scrollHeight,slot:[...document.querySelectorAll('.reel-slot')].map(e=>({h:e.clientHeight,sh:e.scrollHeight})),font:parseFloat(getComputedStyle(document.querySelector('#result-disc')).fontSize)}));assert.ok(result.sw<=result.w&&result.sh<=result.h+1,JSON.stringify(result));assert.ok(result.slot.every(s=>s.sh<=s.h+1),JSON.stringify(result));assert.ok(result.font>=19);report.layouts.push({description,...result});}
try{
 // Freeze rendering after start, then move only the input clock. The previously
 // enabled button must reject a late synthetic click without relying on a frame.
 for(const stage of ['disc','stability','shot'])for(const offset of [-.001,0,.001]){
  const p=await page();await seed(p,stage);await p.clock.install({time:new Date('2026-10-04T12:00:00Z')});await p.clock.pauseAt(new Date('2026-10-04T12:00:01Z'));await start(p);
  const before=(await saved(p)).events.filter(e=>e.type==='challenge.choose').length;
  const result=await p.evaluate(offset=>{const s=JSON.parse(localStorage.getItem('disc-roller.league.v1'));Date.now=()=>s.draft.spin.startedAt+3800/3+offset;const b=document.querySelector('#mainAction');b.dispatchEvent(new MouseEvent('click',{bubbles:true}));return {label:document.querySelector('#actionLabel').textContent,disabled:b.disabled};},offset);
  if(offset<0)assert.equal(result.label,'LOCKED');else{assert.equal(result.label,'LET IT SPIN');assert.ok(result.disabled);assert.equal((await saved(p)).events.filter(e=>e.type==='challenge.choose').length,before);}
  await p.context().close();
 }
 report.checks.push('All three stages reject manual clicks at/after exact one-third; accept just before, even without a fresh animation frame');
 const p=await page();await start(p);const initial=(await saved(p)).draft.spin;await p.waitForTimeout(1450);assert.equal(await p.locator('#actionLabel').innerText(),'LET IT SPIN');assert.ok(await p.locator('#mainAction').isDisabled());
 await p.evaluate(()=>{const b=document.querySelector('#mainAction');for(let i=0;i<5;i++)b.dispatchEvent(new MouseEvent('click',{bubbles:true}));});assert.equal((await saved(p)).draft.stage,'disc');
 await p.locator('#openHelp').click();await p.waitForTimeout(200);await p.keyboard.press('Escape');await p.waitForFunction(()=>!document.querySelector('dialog[open]'));await p.locator('#mainAction').click();assert.equal(await p.locator('#actionLabel').innerText(),'LET IT SPIN');assert.deepEqual((await saved(p)).draft.spin,initial);
 await p.reload();assert.equal(await p.locator('#actionLabel').innerText(),'RESUME');await p.locator('#mainAction').click();assert.deepEqual((await saved(p)).draft.spin,initial);assert.notEqual(await p.locator('#actionLabel').innerText(),'QUICK STOP');await p.waitForFunction(()=>JSON.parse(localStorage.getItem('disc-roller.league.v1')).draft.stage==='complete',null,{timeout:20000});assert.equal((await saved(p)).rounds[0].challenges.length,1);
 report.checks.push('Late/repeated clicks blocked; menu and saved reload resume same deadline; auto-end completes all stages once');
 const reduced=await page({reducedMotion:'reduce'});await start(reduced);await reduced.waitForTimeout(1400);assert.equal(await reduced.locator('#actionLabel').innerText(),'LET IT SPIN');await reduced.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});const paused=(await saved(reduced)).draft.spin;await reduced.waitForTimeout(100);await reduced.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));});await reduced.locator('#mainAction').click();assert.deepEqual((await saved(reduced)).draft.spin,paused);assert.notEqual(await reduced.locator('#actionLabel').innerText(),'QUICK STOP');
 report.checks.push('Reduced motion and background/resume obey the same closed window');
 const ui=await page();await ui.evaluate(async()=>{const m=await import('./model.js');let s=m.freshState();for(const name of ['Alex','Taylor','Jordan'])s=m.applyCommand(s,'player.add',{name});s=m.applyCommand(s,'score.set',{playerId:s.players[0].id,holeId:s.activeHoleId,strokes:4});s=m.applyCommand(s,'challenge.start');s=m.applyCommand(s,'challenge.choose',{value:'Putter'});localStorage.setItem(m.STORAGE_KEY,JSON.stringify(s));});await ui.reload();
 assert.equal(await ui.locator('html').getAttribute('data-theme'),'day');
 for(const theme of ['day','night']){
  if(await ui.locator('html').getAttribute('data-theme')!==theme)await ui.locator('#rollerScreen [data-theme-toggle]').click();
  for(const [width,height] of [[320,480],[390,740],[667,375],[1280,800]]){await ui.setViewportSize({width,height});await fit(ui,theme);}
  await ui.setViewportSize({width:390,height:740});await ui.screenshot({path:`review/revision-${theme}-roller.png`});
  await ui.locator('#openScores').click();await ui.screenshot({path:`review/revision-${theme}-scores.png`});assert.equal(await ui.locator('#scoreGrid tbody tr').count(),3);assert.equal(await ui.locator('#scoreGrid thead button').count(),9);await ui.getByRole('button',{name:'Enter scores for hole 2',exact:true}).click();await ui.waitForFunction(()=>document.querySelector('#holeDialog').open);
  const before=JSON.stringify(await saved(ui));const wheel=ui.locator('.stroke-wheel').first();await wheel.focus();await ui.keyboard.press('Home');await ui.keyboard.press('ArrowDown');await ui.keyboard.press('ArrowDown');await ui.keyboard.press('ArrowDown');assert.equal(await wheel.getAttribute('data-value'),'3');assert.equal(JSON.stringify(await saved(ui)),before);await ui.screenshot({path:`review/revision-${theme}-wheel.png`});
  await ui.locator('#holeDialog .close-button').click();await ui.waitForFunction(()=>document.querySelector('#scoresDialog').open);assert.equal(JSON.stringify(await saved(ui)),before);await ui.getByRole('button',{name:'Enter scores for hole 2',exact:true}).click();await ui.waitForFunction(()=>document.querySelector('#holeDialog').open);await ui.locator('.stroke-wheel').first().evaluate(e=>{e.scrollTop=5*48;e.dispatchEvent(new Event('scroll'));});await ui.locator('#saveHole').click();await ui.waitForFunction(()=>document.querySelector('#scoresDialog').open);
  assert.ok(await ui.getByRole('button',{name:'Alex, hole 2: 5. Edit score',exact:true}).isVisible());await ui.locator('#scoresDialog .close-button').click();await ui.waitForFunction(()=>!document.querySelector('dialog[open]'));
 }
 await ui.reload();assert.equal(await ui.locator('html').getAttribute('data-theme'),'night');await ui.context().setOffline(true);await ui.reload();assert.equal(await ui.locator('html').getAttribute('data-theme'),'night');assert.equal((await saved(ui)).rounds[0].scores.length,2);await ui.context().setOffline(false);
 report.checks.push('Day/Night choice persists offline; larger Putter fits 320px and landscape; overview lists all players/holes; wheels use keyboard, cancel preserves data, Save updates totals');
 assert.deepEqual(report.errors,[]);report.passed=true;
}catch(e){report.passed=false;report.failure=e.stack;throw e;}finally{await fs.writeFile('review/revision-results.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();}
