import {createRequire} from 'node:module';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE||'playwright');
const base=(process.env.TEST_URL||'http://127.0.0.1:4173').replace(/\/$/,'');
const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
const report={base,browser:browser.version(),checks:[],errors:[],layouts:[]};
const contexts=[];
await fs.mkdir('review',{recursive:true});
async function page(reduced='no-preference'){const c=await browser.newContext({viewport:{width:390,height:740},reducedMotion:reduced});contexts.push(c);const p=await c.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto(base+'/#play');return p;}
const saved=p=>p.evaluate(()=>JSON.parse(localStorage.getItem('disc-roller.league.v1')));
async function start(p){await p.locator('#mainAction').click();await p.waitForFunction(()=>document.querySelector('#actionLabel').textContent==='STOP');}
async function waitStage(p,stage){await p.waitForFunction(stage=>JSON.parse(localStorage.getItem('disc-roller.league.v1')).draft.stage===stage,stage);}
async function fit(p,label){const d=await p.evaluate(()=>{const b=document.querySelector('#gameDisplay');return {width:innerWidth,height:innerHeight,scrollWidth:document.documentElement.scrollWidth,scrollHeight:document.documentElement.scrollHeight,displayHeight:b.clientHeight,displayScroll:b.scrollHeight}});assert.ok(d.scrollWidth<=d.width&&d.scrollHeight<=d.height+1,JSON.stringify(d));assert.ok(d.displayScroll<=d.displayHeight+2,JSON.stringify(d));report.layouts.push({label,...d});}
try{
 const p=await page();await start(p);await p.waitForTimeout(300);const first=await p.locator('#reelTrack').evaluate(e=>getComputedStyle(e).transform);await p.waitForTimeout(80);const second=await p.locator('#reelTrack').evaluate(e=>getComputedStyle(e).transform);assert.notEqual(first,second);assert.equal(await p.locator('.reel-row').count(),7);assert.ok(await p.locator('#reelWindow').isVisible());await p.screenshot({path:'review/slot-spinning-mobile.png'});
 // Capture and click in the same task: the accepted value must be what was painted.
 const expected=await p.evaluate(()=>{const value=document.querySelector('#reelWindow').dataset.center;document.querySelector('#mainAction').click();document.querySelector('#mainAction').click();document.querySelector('#mainAction').click();return value;});
 assert.equal(await p.locator('#actionLabel').innerText(),'LOCKED');assert.equal(await p.locator('#reelText').innerText(),expected==='WILDCARD'?'WILD CARD':expected);await p.waitForTimeout(620);let s=await saved(p);assert.equal(s.events.filter(e=>e.type==='challenge.choose').length,1);if(expected==='WILDCARD')assert.ok(s.draft.wildcard);else assert.equal(s.draft.disc,expected);
 report.checks.push('Visible translating track; manual early stop matches last painted center; repeated clicks commit once');
 const auto=await page();await start(auto);await waitStage(auto,'complete');s=await saved(auto);assert.deepEqual([s.draft.disc,s.draft.stability,s.draft.shot],['Driver','Neutral','Forehand']);assert.equal(s.rounds[0].challenges.length,1);assert.equal(s.events.filter(e=>e.type==='challenge.choose').length,3);await auto.screenshot({path:'review/slot-auto-complete-mobile.png'});report.checks.push('All three stages auto-stop, retain centered values and commit once');
 const interrupted=await page();await start(interrupted);await interrupted.waitForTimeout(250);await interrupted.locator('#openHelp').click();const paused=await interrupted.locator('#reelTrack').getAttribute('style');await interrupted.waitForTimeout(4400);assert.equal((await saved(interrupted)).events.filter(e=>e.type==='challenge.choose').length,0);assert.equal(await interrupted.locator('#reelTrack').getAttribute('style'),paused);await interrupted.keyboard.press('Escape');await interrupted.waitForFunction(()=>document.querySelector('#actionLabel').textContent==='RESUME');await start(interrupted);
 await interrupted.evaluate(()=>{document.querySelector('#mainAction').click();document.querySelector('#openScores').click();});await interrupted.waitForTimeout(700);assert.equal((await saved(interrupted)).events.filter(e=>e.type==='challenge.choose').length,0);await interrupted.keyboard.press('Escape');await interrupted.waitForFunction(()=>document.querySelector('#actionLabel').textContent==='RESUME');await interrupted.reload();assert.equal(await interrupted.locator('#actionLabel').innerText(),'RESUME');report.checks.push('Menus cancel animation and settling callbacks; no hidden commits; reload resumes unfinished stage');
 await start(interrupted);await interrupted.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});await interrupted.waitForTimeout(4400);assert.equal((await saved(interrupted)).events.filter(e=>e.type==='challenge.choose').length,0);await interrupted.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));});assert.equal(await interrupted.locator('#actionLabel').innerText(),'RESUME');report.checks.push('Background visibility cancellation leaves no auto-stop timer');
 const reduced=await page('reduce');await start(reduced);assert.ok(await reduced.locator('#reelWindow').isHidden());assert.ok(await reduced.locator('#reelText').isVisible());await waitStage(reduced,'complete');assert.equal((await saved(reduced)).rounds[0].challenges.length,1);report.checks.push('Reduced motion still auto-stops all stages without scrolling');
 const lp=await page();for(const [width,height] of [[320,480],[320,568],[390,664],[667,375],[1280,800]]){await lp.setViewportSize({width,height});await lp.reload();if((await lp.locator('#actionLabel').innerText())==='ROLL')await start(lp);else await start(lp);await lp.waitForTimeout(250);await fit(lp,'spinning');await lp.locator('#openHelp').click();await lp.keyboard.press('Escape');await lp.waitForFunction(()=>document.querySelector('#actionLabel').textContent==='RESUME');await fit(lp,'paused');}await lp.setViewportSize({width:390,height:740});await lp.reload();await start(lp);await lp.waitForTimeout(3400);await lp.screenshot({path:'review/slot-slowing-mobile.png'});report.checks.push('Moving reel fits 320px, short mobile viewport, landscape and desktop');
 assert.deepEqual(report.errors,[]);report.passed=true;
}catch(e){report.passed=false;report.failure=e.stack;throw e;}finally{await fs.writeFile('review/slot-results.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));for(const c of contexts)await c.close();await browser.close();}
